"""Fractal Flight Studio."""

from .camera import CameraState
from .ffmpeg_mp4 import (
    FFmpegInfo,
    FFmpegNotFoundError,
    FFmpegProbeError,
    Mp4ExportCancelled,
    Mp4ExportError,
    Mp4ExportPlan,
    Mp4ExportProgress,
    Mp4ExportResult,
    Mp4ExportSettings,
    encode_mp4_frames,
    probe_ffmpeg,
)
from .export_controller import (
    FlightExportConfiguration,
    FlightExportController,
    FlightExportJobKind,
    FlightExportProgress,
    flight_export_fingerprint,
    parse_frame_rate,
)
from .flight_path import (
    CameraPath,
    CenterInterpolation,
    Easing,
    FlightKeyframe,
)
from .models import FractalKind, Precision, RenderMode, RenderRequest, Viewport
from .mp4_export import build_mp4_export_plan, export_path_to_mp4
from .path_editor import CameraPathDraft
from .offline_render import (
    OfflineFrame,
    OfflineFrameJob,
    OfflineFramePlan,
    OfflineFrameRenderError,
    OfflineRenderSettings,
    build_offline_frame_plan,
    iter_offline_frame_jobs,
    render_offline_frame,
    render_offline_frames,
)
from .preflight import (
    PreflightCancelled,
    PreflightIssue,
    PreflightIssueKind,
    PreflightPlan,
    PreflightReport,
    PreflightSample,
    PreflightSettings,
    build_preflight_plan,
    run_path_preflight,
)

__all__ = [
    "CameraPath",
    "CameraPathDraft",
    "CameraState",
    "CenterInterpolation",
    "Easing",
    "FFmpegInfo",
    "FFmpegNotFoundError",
    "FFmpegProbeError",
    "FlightExportConfiguration",
    "FlightExportController",
    "FlightExportJobKind",
    "FlightExportProgress",
    "FlightKeyframe",
    "FractalKind",
    "Mp4ExportCancelled",
    "Mp4ExportError",
    "Mp4ExportPlan",
    "Mp4ExportProgress",
    "Mp4ExportResult",
    "Mp4ExportSettings",
    "OfflineFrame",
    "OfflineFrameJob",
    "OfflineFramePlan",
    "OfflineFrameRenderError",
    "OfflineRenderSettings",
    "Precision",
    "PreflightCancelled",
    "PreflightIssue",
    "PreflightIssueKind",
    "PreflightPlan",
    "PreflightReport",
    "PreflightSample",
    "PreflightSettings",
    "RenderMode",
    "RenderRequest",
    "Viewport",
    "build_mp4_export_plan",
    "build_offline_frame_plan",
    "build_preflight_plan",
    "encode_mp4_frames",
    "export_path_to_mp4",
    "flight_export_fingerprint",
    "iter_offline_frame_jobs",
    "parse_frame_rate",
    "probe_ffmpeg",
    "render_offline_frame",
    "render_offline_frames",
    "run_path_preflight",
]
__version__ = "0.9.0"
