"""Fractal Flight Studio."""

from .camera import CameraState
from .ffmpeg_mp4 import (
    FFmpegInfo,
    FFmpegNotFoundError,
    FFmpegProbeError,
    Mp4ExportCancelled,
    Mp4ExportError,
    Mp4ExportPlan,
    Mp4ExportProgress,
    Mp4ExportResult,
    Mp4ExportSettings,
    encode_mp4_frames,
    probe_ffmpeg,
)
from .export_controller import (
    FlightExportConfiguration,
    FlightExportController,
    FlightExportJobKind,
    FlightExportProgress,
    flight_export_fingerprint,
    parse_frame_rate,
)
from .flight_path import (
    CameraPath,
    CenterInterpolation,
    Easing,
    FlightKeyframe,
)
from .flight_plan import (
    EvaluatedFlightFrame,
    EvaluatedRenderState,
    FlightPlanDefaults,
    FlightPlanDocument,
    FlightScene,
    PaletteTransition,
    RenderCue,
    RenderProfile,
    RenderTrack,
)
from .flight_plan_io import (
    FLIGHT_PLAN_EXTENSION,
    FLIGHT_PLAN_FORMAT,
    FLIGHT_PLAN_SCHEMA_VERSION,
    FlightPlanError,
    FlightPlanFormatError,
    deserialize_flight_plan,
    flight_plan_to_dict,
    load_flight_plan,
    save_flight_plan,
    serialize_flight_plan,
    suggested_flight_plan_name,
)
from .flight_plan_session import FlightPlanSession
from .flight_plan_playback import (
    FlightPlanPlaybackController,
    PlaybackSample,
    PlaybackState,
)
from .models import FractalKind, Precision, RenderMode, RenderRequest, Viewport
from .palettes import PaletteBlend
from .mp4_export import build_mp4_export_plan, export_path_to_mp4
from .path_editor import CameraPathDraft
from .offline_render import (
    OfflineFrame,
    OfflineFrameJob,
    OfflineFramePlan,
    OfflineFrameRenderError,
    OfflineRenderSettings,
    build_offline_frame_plan,
    iter_offline_frame_jobs,
    render_offline_frame,
    render_offline_frames,
)
from .temporal_tonemapping import (
    TemporalToneSettings,
    ToneAnalysisProgress,
    ToneStability,
    analyze_offline_tone_states,
    stabilize_tone_states,
)
from .preflight import (
    PreflightCancelled,
    PreflightIssue,
    PreflightIssueKind,
    PreflightPlan,
    PreflightReport,
    PreflightSample,
    PreflightSettings,
    build_preflight_plan,
    run_path_preflight,
)

__all__ = [
    "CameraPath",
    "CameraPathDraft",
    "CameraState",
    "CenterInterpolation",
    "Easing",
    "EvaluatedFlightFrame",
    "EvaluatedRenderState",
    "FFmpegInfo",
    "FFmpegNotFoundError",
    "FFmpegProbeError",
    "FlightExportConfiguration",
    "FlightExportController",
    "FlightExportJobKind",
    "FlightExportProgress",
    "FlightKeyframe",
    "FlightPlanDefaults",
    "FlightPlanDocument",
    "FlightPlanError",
    "FlightPlanFormatError",
    "FlightPlanPlaybackController",
    "FlightPlanSession",
    "FlightScene",
    "FLIGHT_PLAN_EXTENSION",
    "FLIGHT_PLAN_FORMAT",
    "FLIGHT_PLAN_SCHEMA_VERSION",
    "FractalKind",
    "Mp4ExportCancelled",
    "Mp4ExportError",
    "Mp4ExportPlan",
    "Mp4ExportProgress",
    "Mp4ExportResult",
    "Mp4ExportSettings",
    "OfflineFrame",
    "OfflineFrameJob",
    "OfflineFramePlan",
    "OfflineFrameRenderError",
    "OfflineRenderSettings",
    "Precision",
    "PaletteBlend",
    "PaletteTransition",
    "PlaybackSample",
    "PlaybackState",
    "PreflightCancelled",
    "PreflightIssue",
    "PreflightIssueKind",
    "PreflightPlan",
    "PreflightReport",
    "PreflightSample",
    "PreflightSettings",
    "RenderMode",
    "RenderCue",
    "RenderProfile",
    "RenderRequest",
    "RenderTrack",
    "TemporalToneSettings",
    "ToneAnalysisProgress",
    "ToneStability",
    "Viewport",
    "build_mp4_export_plan",
    "analyze_offline_tone_states",
    "build_offline_frame_plan",
    "build_preflight_plan",
    "encode_mp4_frames",
    "deserialize_flight_plan",
    "export_path_to_mp4",
    "flight_plan_to_dict",
    "flight_export_fingerprint",
    "iter_offline_frame_jobs",
    "parse_frame_rate",
    "probe_ffmpeg",
    "load_flight_plan",
    "render_offline_frame",
    "render_offline_frames",
    "run_path_preflight",
    "save_flight_plan",
    "serialize_flight_plan",
    "stabilize_tone_states",
    "suggested_flight_plan_name",
]
__version__ = "0.9.0"
